[package]
name = "proj-sys"
description = "Rust bindings for PROJ v8.2.x"
repository = "https://github.com/georust/proj"
version = "0.21.0"
readme = "README.md"
authors = ["The Georust developers <mods@georust.org>"]
keywords = ["proj", "projection", "osgeo", "geo", "geospatial"]
license = "MIT/Apache-2.0"
edition = "2018"
links = "proj"

[dependencies]

[build-dependencies]
bindgen = "0.59.1"
pkg-config = "0.3.19"
cmake = "0.1"
flate2 = "1.0.14"
tar = "0.4.26"

[features]
nobuild = []
bundled_proj = []
# `pkg_config` feature is deprecated and does nothing
pkg_config = []
network = []

[package.metadata.docs.rs]
features = [ "nobuild" ] # This feature will be enabled during the docs.rs build
